# Generated by Django 5.1.6 on 2025-02-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=200)),
                ('notificationEmail', models.CharField(max_length=200)),
                ('goal', models.IntegerField()),
            ],
        ),
    ]
