# Generated by Django 5.1.6 on 2025-02-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='email',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
